<?php
// ============================================================
// STATE COORDINATOR - EXPORT AS PDF
// ============================================================
require_once '../../config/config.php';
require_once '../../includes/session.php';
require_once '../../includes/functions.php';

SessionManager::start();

if (!SessionManager::isLoggedIn()) {
    header('Location: ../../auth/login.php');
    exit();
}

if (SessionManager::get('role_level') !== 'state') {
    header('Location: ../client-admin/');
    exit();
}

$user_name = SessionManager::get('user_name', 'State Coordinator');
$user_id = SessionManager::get('user_id');
$tenant_id = SessionManager::get('tenant_id');
$state_id = SessionManager::get('state_id');

if (empty($state_id)) {
    $db = getDB();
    try {
        $stmt = $db->prepare("SELECT state_id FROM users WHERE id = ?");
        $stmt->execute([$user_id]);
        $user = $stmt->fetch(PDO::FETCH_ASSOC);
        if ($user && !empty($user['state_id'])) {
            $state_id = $user['state_id'];
            SessionManager::set('state_id', $state_id);
        }
    } catch (Exception $e) {
        error_log("Error fetching state_id: " . $e->getMessage());
    }
}

$db = getDB();

// Get parameters
$type = isset($_GET['type']) ? $_GET['type'] : 'state_report';
$election_id = isset($_GET['election_id']) ? (int)$_GET['election_id'] : 0;
$lga_id = isset($_GET['lga_id']) ? (int)$_GET['lga_id'] : 0;
$period = isset($_GET['period']) ? $_GET['period'] : 'month';

// Get state name
$state_name = 'Unknown State';
if (!empty($state_id)) {
    $stmt = $db->prepare("SELECT name FROM states WHERE id = ?");
    $stmt->execute([$state_id]);
    $state = $stmt->fetch(PDO::FETCH_ASSOC);
    $state_name = $state['name'] ?? 'Unknown State';
}

// Generate PDF content based on type
$html = '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>' . APP_NAME . ' - Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; padding: 20px 0; border-bottom: 2px solid #0F4C81; }
        .header h1 { margin: 0; color: #0F4C81; font-size: 24px; }
        .header p { margin: 5px 0 0; color: #666; font-size: 14px; }
        .report-info { margin: 15px 0; padding: 10px; background: #f5f5f5; border-radius: 5px; }
        .report-info table { width: 100%; }
        .report-info td { padding: 3px 10px; }
        .report-info .label { font-weight: bold; color: #555; }
        table.data { width: 100%; border-collapse: collapse; margin: 15px 0; }
        table.data th { background: #0F4C81; color: white; padding: 8px 10px; text-align: left; font-size: 11px; }
        table.data td { padding: 6px 10px; border-bottom: 1px solid #ddd; }
        table.data tr:nth-child(even) { background: #f9f9f9; }
        .footer { text-align: center; padding: 15px 0; border-top: 1px solid #ddd; margin-top: 20px; font-size: 10px; color: #999; }
        .summary-box { display: flex; flex-wrap: wrap; gap: 10px; margin: 15px 0; }
        .summary-item { flex: 1; min-width: 120px; padding: 10px; background: #f5f5f5; border-radius: 5px; text-align: center; }
        .summary-item .number { font-size: 20px; font-weight: bold; color: #0F4C81; }
        .summary-item .label { font-size: 10px; color: #666; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 10px; font-weight: bold; }
        .badge-success { background: #d4edda; color: #155724; }
        .badge-warning { background: #fff3cd; color: #856404; }
        .badge-danger { background: #f8d7da; color: #721c24; }
        .badge-info { background: #d1ecf1; color: #0c5460; }
    </style>
</head>
<body>';

// Add report header
$html .= '
    <div class="header">
        <h1>' . APP_NAME . '</h1>
        <p>' . htmlspecialchars($state_name) . ' State - ' . ucfirst(str_replace('_', ' ', $type)) . '</p>
    </div>
    <div class="report-info">
        <table>
            <tr>
                <td class="label">Generated By:</td>
                <td>' . htmlspecialchars($user_name) . '</td>
                <td class="label">Date:</td>
                <td>' . date('F j, Y g:i A') . '</td>
            </tr>
            <tr>
                <td class="label">Report Type:</td>
                <td>' . ucfirst(str_replace('_', ' ', $type)) . '</td>
                <td class="label">Period:</td>
                <td>' . ucfirst($period) . '</td>
            </tr>
        </table>
    </div>';

try {
    switch ($type) {
        case 'state_report':
            // State Report Content
            $html .= '<h2>State Summary</h2>';
            
            // Get stats
            $stats = [];
            $stmt = $db->prepare("SELECT COUNT(*) as count FROM lgas WHERE state_id = ? AND is_active = 1");
            $stmt->execute([$state_id]);
            $stats['total_lgas'] = (int)($stmt->fetch(PDO::FETCH_ASSOC)['count'] ?? 0);
            
            $stmt = $db->prepare("
                SELECT COUNT(*) as count 
                FROM polling_units pu
                JOIN wards w ON pu.ward_id = w.id
                JOIN lgas l ON w.lga_id = l.id
                WHERE l.state_id = ? AND pu.is_active = 1
            ");
            $stmt->execute([$state_id]);
            $stats['total_pus'] = (int)($stmt->fetch(PDO::FETCH_ASSOC)['count'] ?? 0);
            
            $stmt = $db->prepare("
                SELECT COUNT(*) as count 
                FROM users u 
                JOIN roles r ON u.role_id = r.id 
                WHERE r.level IN ('lga', 'ward', 'pu_agent') 
                AND u.state_id = ? AND u.status = 'active' AND u.deleted_at IS NULL
            ");
            $stmt->execute([$state_id]);
            $stats['total_personnel'] = (int)($stmt->fetch(PDO::FETCH_ASSOC)['count'] ?? 0);
            
            $stmt = $db->prepare("
                SELECT COUNT(*) as count 
                FROM elections 
                WHERE tenant_id = ? AND deleted_at IS NULL
                AND (states_json LIKE ? OR states_json IS NULL OR states_json = '[]')
            ");
            $stmt->execute([$tenant_id, '%"' . $state_id . '"%']);
            $stats['total_elections'] = (int)($stmt->fetch(PDO::FETCH_ASSOC)['count'] ?? 0);
            
            // Results
            $sql = "
                SELECT 
                    COUNT(*) as total,
                    SUM(CASE WHEN status IN ('verified', 'approved') THEN 1 ELSE 0 END) as verified
                FROM results_ec8a r
                JOIN polling_units pu ON r.pu_id = pu.id
                JOIN wards w ON pu.ward_id = w.id
                JOIN lgas l ON w.lga_id = l.id
                WHERE l.state_id = ? AND r.tenant_id = ?
            ";
            $params = [$state_id, $tenant_id];
            if ($election_id > 0) {
                $sql .= " AND r.election_id = ?";
                $params[] = $election_id;
            }
            $stmt = $db->prepare($sql);
            $stmt->execute($params);
            $result_stats = $stmt->fetch(PDO::FETCH_ASSOC);
            $stats['total_results'] = (int)($result_stats['total'] ?? 0);
            $stats['verified_results'] = (int)($result_stats['verified'] ?? 0);
            
            $html .= '
                <div class="summary-box">
                    <div class="summary-item">
                        <div class="number">' . number_format($stats['total_lgas']) . '</div>
                        <div class="label">LGAs</div>
                    </div>
                    <div class="summary-item">
                        <div class="number">' . number_format($stats['total_pus']) . '</div>
                        <div class="label">Polling Units</div>
                    </div>
                    <div class="summary-item">
                        <div class="number">' . number_format($stats['total_personnel']) . '</div>
                        <div class="label">Personnel</div>
                    </div>
                    <div class="summary-item">
                        <div class="number">' . number_format($stats['total_elections']) . '</div>
                        <div class="label">Elections</div>
                    </div>
                    <div class="summary-item">
                        <div class="number">' . number_format($stats['total_results']) . '</div>
                        <div class="label">Results Submitted</div>
                    </div>
                    <div class="summary-item">
                        <div class="number">' . number_format($stats['verified_results']) . '</div>
                        <div class="label">Verified Results</div>
                    </div>
                </div>';
            
            // LGA-wise table
            $html .= '<h3>LGA-wise Breakdown</h3>';
            $stmt = $db->prepare("
                SELECT 
                    l.id, l.name,
                    COUNT(DISTINCT pu.id) as total_pus,
                    COUNT(DISTINCT r.id) as total_results,
                    COUNT(DISTINCT u.id) as coordinators
                FROM lgas l
                LEFT JOIN wards w ON w.lga_id = l.id AND w.is_active = 1
                LEFT JOIN polling_units pu ON pu.ward_id = w.id AND pu.is_active = 1
                LEFT JOIN results_ec8a r ON r.pu_id = pu.id AND r.tenant_id = ?
                LEFT JOIN users u ON u.lga_id = l.id AND u.status = 'active'
                WHERE l.state_id = ? AND l.is_active = 1
                GROUP BY l.id, l.name
                ORDER BY l.name ASC
            ");
            $stmt->execute([$tenant_id, $state_id]);
            $lgas = $stmt->fetchAll(PDO::FETCH_ASSOC);
            
            $html .= '
                <table class="data">
                    <thead>
                        <tr>
                            <th>LGA</th>
                            <th>PUs</th>
                            <th>Results</th>
                            <th>Coordinators</th>
                            <th>Reporting Rate</th>
                        </tr>
                    </thead>
                    <tbody>';
            foreach ($lgas as $lga) {
                $rate = $lga['total_pus'] > 0 ? round(($lga['total_results'] / $lga['total_pus']) * 100, 1) : 0;
                $badge_class = $rate >= 70 ? 'badge-success' : ($rate >= 40 ? 'badge-warning' : 'badge-danger');
                $html .= '
                        <tr>
                            <td>' . htmlspecialchars($lga['name']) . '</td>
                            <td>' . number_format($lga['total_pus']) . '</td>
                            <td>' . number_format($lga['total_results']) . '</td>
                            <td>' . number_format($lga['coordinators']) . '</td>
                            <td><span class="badge ' . $badge_class . '">' . $rate . '%</span></td>
                        </tr>';
            }
            $html .= '
                    </tbody>
                </table>';
            break;
            
        case 'lga_performance':
            // LGA Performance Report
            $lga_name = 'All LGAs';
            if ($lga_id > 0) {
                $stmt = $db->prepare("SELECT name FROM lgas WHERE id = ?");
                $stmt->execute([$lga_id]);
                $l = $stmt->fetch(PDO::FETCH_ASSOC);
                $lga_name = $l['name'] ?? 'All LGAs';
            }
            
            $html .= '<h2>LGA Performance Report</h2>';
            $html .= '<p><strong>LGA:</strong> ' . htmlspecialchars($lga_name) . '</p>';
            
            // Get performance data
            $sql = "
                SELECT 
                    l.id, l.name as lga_name,
                    COUNT(DISTINCT pu.id) as total_pus,
                    COUNT(DISTINCT r.id) as reported_pus,
                    COUNT(DISTINCT CASE WHEN r.status IN ('verified', 'approved') THEN r.id END) as verified_pus,
                    COUNT(DISTINCT i.id) as total_incidents,
                    COUNT(DISTINCT u.id) as total_coordinators,
                    COUNT(DISTINCT a.id) as total_agents
                FROM lgas l
                LEFT JOIN wards w ON w.lga_id = l.id AND w.is_active = 1
                LEFT JOIN polling_units pu ON pu.ward_id = w.id AND pu.is_active = 1
                LEFT JOIN results_ec8a r ON r.pu_id = pu.id AND r.tenant_id = ?
                LEFT JOIN incidents i ON i.lga_id = l.id
                LEFT JOIN users u ON u.lga_id = l.id AND u.role_id IN (SELECT id FROM roles WHERE level = 'lga')
                LEFT JOIN users a ON a.lga_id = l.id AND a.role_id IN (SELECT id FROM roles WHERE level = 'pu_agent')
                WHERE l.state_id = ? AND l.is_active = 1
            ";
            $params = [$tenant_id, $state_id];
            if ($lga_id > 0) {
                $sql .= " AND l.id = ?";
                $params[] = $lga_id;
            }
            $sql .= " GROUP BY l.id, l.name ORDER BY l.name ASC";
            
            $stmt = $db->prepare($sql);
            $stmt->execute($params);
            $lgas = $stmt->fetchAll(PDO::FETCH_ASSOC);
            
            $html .= '
                <table class="data">
                    <thead>
                        <tr>
                            <th>LGA</th>
                            <th>Total PUs</th>
                            <th>Reported</th>
                            <th>Verified</th>
                            <th>Incidents</th>
                            <th>Coordinators</th>
                            <th>Agents</th>
                            <th>Rate</th>
                        </tr>
                    </thead>
                    <tbody>';
            foreach ($lgas as $lga) {
                $rate = $lga['total_pus'] > 0 ? round(($lga['reported_pus'] / $lga['total_pus']) * 100, 1) : 0;
                $badge_class = $rate >= 70 ? 'badge-success' : ($rate >= 40 ? 'badge-warning' : 'badge-danger');
                $html .= '
                        <tr>
                            <td>' . htmlspecialchars($lga['lga_name']) . '</td>
                            <td>' . number_format($lga['total_pus']) . '</td>
                            <td>' . number_format($lga['reported_pus']) . '</td>
                            <td>' . number_format($lga['verified_pus']) . '</td>
                            <td>' . number_format($lga['total_incidents']) . '</td>
                            <td>' . number_format($lga['total_coordinators']) . '</td>
                            <td>' . number_format($lga['total_agents']) . '</td>
                            <td><span class="badge ' . $badge_class . '">' . $rate . '%</span></td>
                        </tr>';
            }
            $html .= '
                    </tbody>
                </table>';
            break;
            
        case 'election_report':
            // Election Report
            $election_name = 'All Elections';
            if ($election_id > 0) {
                $stmt = $db->prepare("SELECT name, election_date FROM elections WHERE id = ?");
                $stmt->execute([$election_id]);
                $e = $stmt->fetch(PDO::FETCH_ASSOC);
                $election_name = $e['name'] ?? 'All Elections';
                $election_date = $e['election_date'] ?? null;
            }
            
            $html .= '<h2>Election Report</h2>';
            $html .= '<p><strong>Election:</strong> ' . htmlspecialchars($election_name) . '</p>';
            if (isset($election_date)) {
                $html .= '<p><strong>Date:</strong> ' . date('F j, Y', strtotime($election_date)) . '</p>';
            }
            
            // Get election results
            $sql = "
                SELECT 
                    l.name as lga_name,
                    COUNT(DISTINCT pu.id) as total_pus,
                    COUNT(DISTINCT r.id) as submitted_results,
                    COUNT(DISTINCT CASE WHEN r.status IN ('verified', 'approved') THEN r.id END) as verified_results,
                    COUNT(DISTINCT CASE WHEN r.status = 'approved' THEN r.id END) as approved_results,
                    SUM(r.valid_votes) as valid_votes
                FROM lgas l
                LEFT JOIN wards w ON w.lga_id = l.id AND w.is_active = 1
                LEFT JOIN polling_units pu ON pu.ward_id = w.id AND pu.is_active = 1
                LEFT JOIN results_ec8a r ON r.pu_id = pu.id AND r.election_id = ? AND r.tenant_id = ?
                WHERE l.state_id = ? AND l.is_active = 1
                GROUP BY l.id, l.name
                ORDER BY l.name ASC
            ";
            $params = [$election_id, $tenant_id, $state_id];
            $stmt = $db->prepare($sql);
            $stmt->execute($params);
            $lgas = $stmt->fetchAll(PDO::FETCH_ASSOC);
            
            $html .= '
                <table class="data">
                    <thead>
                        <tr>
                            <th>LGA</th>
                            <th>PUs</th>
                            <th>Submitted</th>
                            <th>Verified</th>
                            <th>Approved</th>
                            <th>Valid Votes</th>
                            <th>Rate</th>
                        </tr>
                    </thead>
                    <tbody>';
            foreach ($lgas as $lga) {
                $rate = $lga['total_pus'] > 0 ? round(($lga['submitted_results'] / $lga['total_pus']) * 100, 1) : 0;
                $badge_class = $rate >= 70 ? 'badge-success' : ($rate >= 40 ? 'badge-warning' : 'badge-danger');
                $html .= '
                        <tr>
                            <td>' . htmlspecialchars($lga['lga_name']) . '</td>
                            <td>' . number_format($lga['total_pus']) . '</td>
                            <td>' . number_format($lga['submitted_results']) . '</td>
                            <td>' . number_format($lga['verified_results']) . '</td>
                            <td>' . number_format($lga['approved_results']) . '</td>
                            <td>' . number_format($lga['valid_votes']) . '</td>
                            <td><span class="badge ' . $badge_class . '">' . $rate . '%</span></td>
                        </tr>';
            }
            $html .= '
                    </tbody>
                </table>';
            break;
            
        case 'incident_report':
            // Incident Report
            $html .= '<h2>Incident Report</h2>';
            $html .= '<p><strong>Period:</strong> ' . ucfirst($period) . '</p>';
            
            // Get incident stats
            $date_filter = "";
            switch ($period) {
                case 'today':
                    $date_filter = "DATE(created_at) = CURDATE()";
                    break;
                case 'week':
                    $date_filter = "created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY)";
                    break;
                case 'month':
                    $date_filter = "created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)";
                    break;
                case 'quarter':
                    $date_filter = "created_at >= DATE_SUB(NOW(), INTERVAL 90 DAY)";
                    break;
                default:
                    $date_filter = "1=1";
            }
            
            $sql = "
                SELECT 
                    incident_type,
                    severity,
                    status,
                    COUNT(*) as count
                FROM incidents
                WHERE tenant_id = ? AND state_id = ? AND $date_filter
            ";
            $params = [$tenant_id, $state_id];
            if ($election_id > 0) {
                $sql .= " AND election_id = ?";
                $params[] = $election_id;
            }
            $sql .= " GROUP BY incident_type, severity, status ORDER BY count DESC";
            
            $stmt = $db->prepare($sql);
            $stmt->execute($params);
            $incidents = $stmt->fetchAll(PDO::FETCH_ASSOC);
            
            $html .= '
                <table class="data">
                    <thead>
                        <tr>
                            <th>Type</th>
                            <th>Severity</th>
                            <th>Status</th>
                            <th>Count</th>
                        </tr>
                    </thead>
                    <tbody>';
            foreach ($incidents as $inc) {
                $severity_class = $inc['severity'] === 'critical' || $inc['severity'] === 'high' ? 'badge-danger' : ($inc['severity'] === 'medium' ? 'badge-warning' : 'badge-info');
                $html .= '
                        <tr>
                            <td>' . ucfirst(str_replace('_', ' ', $inc['incident_type'])) . '</td>
                            <td><span class="badge ' . $severity_class . '">' . ucfirst($inc['severity']) . '</span></td>
                            <td>' . ucfirst(str_replace('_', ' ', $inc['status'])) . '</td>
                            <td>' . number_format($inc['count']) . '</td>
                        </tr>';
            }
            $html .= '
                    </tbody>
                </table>';
            break;
            
        case 'coordinators_report':
            // Coordinators Report
            $html .= '<h2>Coordinators Report</h2>';
            
            $sql = "
                SELECT 
                    r.level as role_level,
                    COUNT(*) as total,
                    SUM(CASE WHEN u.status = 'active' THEN 1 ELSE 0 END) as active
                FROM users u
                JOIN roles r ON u.role_id = r.id
                WHERE u.tenant_id = ? AND u.state_id = ? AND u.deleted_at IS NULL
                AND r.level IN ('lga', 'ward', 'pu_agent', 'party_agent')
                GROUP BY r.level
            ";
            $params = [$tenant_id, $state_id];
            if ($lga_id > 0) {
                $sql = str_replace("u.state_id = ?", "u.state_id = ? AND u.lga_id = ?", $sql);
                $params[] = $lga_id;
            }
            $stmt = $db->prepare($sql);
            $stmt->execute($params);
            $roles = $stmt->fetchAll(PDO::FETCH_ASSOC);
            
            $role_labels = [
                'lga' => 'LGA Coordinators',
                'ward' => 'Ward Coordinators',
                'pu_agent' => 'PU Agents',
                'party_agent' => 'Party Agents'
            ];
            
            $html .= '
                <table class="data">
                    <thead>
                        <tr>
                            <th>Role</th>
                            <th>Total</th>
                            <th>Active</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>';
            foreach ($roles as $role) {
                $rate = $role['total'] > 0 ? round(($role['active'] / $role['total']) * 100, 1) : 0;
                $badge_class = $rate >= 70 ? 'badge-success' : ($rate >= 40 ? 'badge-warning' : 'badge-danger');
                $html .= '
                        <tr>
                            <td>' . ($role_labels[$role['role_level']] ?? ucfirst($role['role_level'])) . '</td>
                            <td>' . number_format($role['total']) . '</td>
                            <td>' . number_format($role['active']) . '</td>
                            <td><span class="badge ' . $badge_class . '">' . $rate . '%</span></td>
                        </tr>';
            }
            $html .= '
                    </tbody>
                </table>';
            break;
            
        default:
            $html .= '<p>Invalid report type.</p>';
    }
} catch (Exception $e) {
    $html .= '<p>Error generating report: ' . $e->getMessage() . '</p>';
    error_log("PDF Export Error: " . $e->getMessage());
}

$html .= '
    <div class="footer">
        Generated on ' . date('F j, Y g:i A') . ' | ' . APP_NAME . ' &copy; ' . date('Y') . ' All Rights Reserved.
    </div>
</body>
</html>';

// Use a simple PDF generation method - TCPDF or DOMPDF would be better
// For this example, we'll output as HTML that can be printed to PDF
header('Content-Type: text/html');
header('Content-Disposition: attachment; filename="' . $type . '_' . date('Y-m-d') . '.html"');
echo $html;
exit;
?>