<?php
// ============================================================
// LGA COORDINATOR - EXPORT AS PDF
// ============================================================
require_once '../../config/config.php';
require_once '../../includes/session.php';
require_once '../../includes/functions.php';

SessionManager::start();

if (!SessionManager::isLoggedIn()) {
    header('Location: ../../auth/login.php');
    exit();
}

if (SessionManager::get('role_level') !== 'lga') {
    header('Location: ../client-admin/');
    exit();
}

$user_name = SessionManager::get('user_name', 'LGA Coordinator');
$user_id = SessionManager::get('user_id');
$tenant_id = SessionManager::get('tenant_id');
$lga_id = SessionManager::get('lga_id');

if (empty($lga_id)) {
    $db = getDB();
    try {
        $stmt = $db->prepare("SELECT lga_id FROM users WHERE id = ?");
        $stmt->execute([$user_id]);
        $user = $stmt->fetch(PDO::FETCH_ASSOC);
        if ($user && !empty($user['lga_id'])) {
            $lga_id = $user['lga_id'];
            SessionManager::set('lga_id', $lga_id);
        }
    } catch (Exception $e) {
        error_log("Error fetching lga_id: " . $e->getMessage());
    }
}

$db = getDB();

// Get parameters
$type = isset($_GET['type']) ? $_GET['type'] : 'lga_report';
$ward_id = isset($_GET['ward_id']) ? (int)$_GET['ward_id'] : 0;

// Get LGA name
$lga_name = 'LGA';
$state_name = 'State';
try {
    if ($lga_id) {
        $stmt = $db->prepare("
            SELECT l.name as lga_name, s.name as state_name 
            FROM lgas l 
            JOIN states s ON l.state_id = s.id 
            WHERE l.id = ?
        ");
        $stmt->execute([$lga_id]);
        $result = $stmt->fetch(PDO::FETCH_ASSOC);
        if ($result) {
            $lga_name = $result['lga_name'];
            $state_name = $result['state_name'];
        }
    }
} catch (Exception $e) {
    error_log("Error fetching LGA/State: " . $e->getMessage());
}

// Generate PDF content
$html = '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>' . APP_NAME . ' - Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; padding: 20px 0; border-bottom: 2px solid #0F4C81; }
        .header h1 { margin: 0; color: #0F4C81; font-size: 22px; }
        .header p { margin: 5px 0 0; color: #666; font-size: 14px; }
        .report-info { margin: 15px 0; padding: 10px; background: #f5f5f5; border-radius: 5px; }
        .report-info table { width: 100%; }
        .report-info td { padding: 3px 10px; }
        .report-info .label { font-weight: bold; color: #555; }
        table.data { width: 100%; border-collapse: collapse; margin: 15px 0; }
        table.data th { background: #0F4C81; color: white; padding: 6px 8px; text-align: left; font-size: 10px; }
        table.data td { padding: 5px 8px; border-bottom: 1px solid #ddd; font-size: 10px; }
        table.data tr:nth-child(even) { background: #f9f9f9; }
        .footer { text-align: center; padding: 15px 0; border-top: 1px solid #ddd; margin-top: 20px; font-size: 10px; color: #999; }
        .summary-box { display: flex; flex-wrap: wrap; gap: 10px; margin: 15px 0; }
        .summary-item { flex: 1; min-width: 100px; padding: 8px; background: #f5f5f5; border-radius: 5px; text-align: center; }
        .summary-item .number { font-size: 18px; font-weight: bold; color: #0F4C81; }
        .summary-item .label { font-size: 9px; color: #666; }
        .badge { display: inline-block; padding: 1px 6px; border-radius: 8px; font-size: 9px; font-weight: bold; }
        .badge-success { background: #d4edda; color: #155724; }
        .badge-warning { background: #fff3cd; color: #856404; }
        .badge-danger { background: #f8d7da; color: #721c24; }
    </style>
</head>
<body>';

// Add report header
$html .= '
    <div class="header">
        <h1>' . APP_NAME . '</h1>
        <p>' . htmlspecialchars($state_name) . ' State - ' . htmlspecialchars($lga_name) . ' LGA</p>
    </div>
    <div class="report-info">
        <table>
            <tr>
                <td class="label">Report Type:</td>
                <td>' . ucfirst(str_replace('_', ' ', $type)) . '</td>
                <td class="label">Generated By:</td>
                <td>' . htmlspecialchars($user_name) . '</td>
            </tr>
            <tr>
                <td class="label">Date:</td>
                <td>' . date('F j, Y g:i A') . '</td>
                <td class="label">LGA:</td>
                <td>' . htmlspecialchars($lga_name) . '</td>
            </tr>
        </table>
    </div>';

try {
    if ($type === 'lga_report') {
        // LGA Report
        $html .= '<h2>LGA Summary</h2>';
        
        // Get stats
        $stats = [];
        $stmt = $db->prepare("SELECT COUNT(*) as count FROM wards WHERE lga_id = ? AND is_active = 1");
        $stmt->execute([$lga_id]);
        $stats['total_wards'] = (int)($stmt->fetch(PDO::FETCH_ASSOC)['count'] ?? 0);
        
        $stmt = $db->prepare("
            SELECT COUNT(*) as count 
            FROM polling_units pu
            JOIN wards w ON pu.ward_id = w.id
            WHERE w.lga_id = ? AND pu.is_active = 1
        ");
        $stmt->execute([$lga_id]);
        $stats['total_pus'] = (int)($stmt->fetch(PDO::FETCH_ASSOC)['count'] ?? 0);
        
        $stmt = $db->prepare("
            SELECT COUNT(*) as count 
            FROM users u 
            JOIN roles r ON u.role_id = r.id 
            WHERE r.level IN ('ward', 'pu_agent') AND u.lga_id = ? AND u.status = 'active'
        ");
        $stmt->execute([$lga_id]);
        $stats['total_personnel'] = (int)($stmt->fetch(PDO::FETCH_ASSOC)['count'] ?? 0);
        
        $stmt = $db->prepare("
            SELECT COUNT(*) as count
            FROM results_ec8a r
            JOIN polling_units pu ON r.pu_id = pu.id
            JOIN wards w ON pu.ward_id = w.id
            WHERE w.lga_id = ? AND r.tenant_id = ?
        ");
        $stmt->execute([$lga_id, $tenant_id]);
        $stats['total_results'] = (int)($stmt->fetch(PDO::FETCH_ASSOC)['count'] ?? 0);
        
        $stmt = $db->prepare("
            SELECT COUNT(*) as count
            FROM incidents i
            WHERE i.lga_id = ?
        ");
        $stmt->execute([$lga_id]);
        $stats['total_incidents'] = (int)($stmt->fetch(PDO::FETCH_ASSOC)['count'] ?? 0);
        
        $html .= '
            <div class="summary-box">
                <div class="summary-item">
                    <div class="number">' . number_format($stats['total_wards']) . '</div>
                    <div class="label">Wards</div>
                </div>
                <div class="summary-item">
                    <div class="number">' . number_format($stats['total_pus']) . '</div>
                    <div class="label">Polling Units</div>
                </div>
                <div class="summary-item">
                    <div class="number">' . number_format($stats['total_personnel']) . '</div>
                    <div class="label">Personnel</div>
                </div>
                <div class="summary-item">
                    <div class="number">' . number_format($stats['total_results']) . '</div>
                    <div class="label">Results</div>
                </div>
                <div class="summary-item">
                    <div class="number">' . number_format($stats['total_incidents']) . '</div>
                    <div class="label">Incidents</div>
                </div>
            </div>';
        
        // Ward-wise table
        $html .= '<h3>Ward-wise Breakdown</h3>';
        $stmt = $db->prepare("
            SELECT 
                w.name,
                w.code,
                COUNT(DISTINCT pu.id) as total_pus,
                COUNT(DISTINCT r.id) as total_results,
                COUNT(DISTINCT u.id) as coordinators
            FROM wards w
            LEFT JOIN polling_units pu ON pu.ward_id = w.id AND pu.is_active = 1
            LEFT JOIN results_ec8a r ON r.pu_id = pu.id AND r.tenant_id = ?
            LEFT JOIN users u ON u.ward_id = w.id AND u.status = 'active'
            WHERE w.lga_id = ? AND w.is_active = 1
            GROUP BY w.id, w.name, w.code
            ORDER BY w.name ASC
        ");
        $stmt->execute([$tenant_id, $lga_id]);
        $wards = $stmt->fetchAll(PDO::FETCH_ASSOC);
        
        $html .= '
            <table class="data">
                <thead>
                    <tr>
                        <th>Ward</th>
                        <th>Code</th>
                        <th>PUs</th>
                        <th>Results</th>
                        <th>Coordinators</th>
                        <th>Reporting Rate</th>
                    </tr>
                </thead>
                <tbody>';
        foreach ($wards as $ward) {
            $rate = $ward['total_pus'] > 0 ? round(($ward['total_results'] / $ward['total_pus']) * 100, 1) : 0;
            $badge_class = $rate >= 70 ? 'badge-success' : ($rate >= 40 ? 'badge-warning' : 'badge-danger');
            $html .= '
                    <tr>
                        <td>' . htmlspecialchars($ward['name']) . '</td>
                        <td>' . htmlspecialchars($ward['code']) . '</td>
                        <td>' . number_format($ward['total_pus']) . '</td>
                        <td>' . number_format($ward['total_results']) . '</td>
                        <td>' . number_format($ward['coordinators']) . '</td>
                        <td><span class="badge ' . $badge_class . '">' . $rate . '%</span></td>
                    </tr>';
        }
        $html .= '
                </tbody>
            </table>';
            
    } elseif ($type === 'ward_report') {
        // Ward Report
        $ward_name = 'All Wards';
        if ($ward_id > 0) {
            $stmt = $db->prepare("SELECT name FROM wards WHERE id = ?");
            $stmt->execute([$ward_id]);
            $w = $stmt->fetch(PDO::FETCH_ASSOC);
            $ward_name = $w['name'] ?? 'All Wards';
        }
        
        $html .= '<h2>Ward Report</h2>';
        $html .= '<p><strong>Ward:</strong> ' . htmlspecialchars($ward_name) . '</p>';
        
        // Get ward data
        $sql = "
            SELECT 
                w.name as ward_name,
                w.code,
                COUNT(DISTINCT pu.id) as total_pus,
                COUNT(DISTINCT r.id) as total_results,
                COUNT(DISTINCT CASE WHEN r.status IN ('verified', 'approved') THEN r.id END) as verified_results,
                COUNT(DISTINCT u.id) as coordinators
            FROM wards w
            LEFT JOIN polling_units pu ON pu.ward_id = w.id AND pu.is_active = 1
            LEFT JOIN results_ec8a r ON r.pu_id = pu.id AND r.tenant_id = ?
            LEFT JOIN users u ON u.ward_id = w.id AND u.status = 'active'
            WHERE w.lga_id = ? AND w.is_active = 1
        ";
        $params = [$tenant_id, $lga_id];
        if ($ward_id > 0) {
            $sql .= " AND w.id = ?";
            $params[] = $ward_id;
        }
        $sql .= " GROUP BY w.id, w.name, w.code ORDER BY w.name ASC";
        
        $stmt = $db->prepare($sql);
        $stmt->execute($params);
        $wards = $stmt->fetchAll(PDO::FETCH_ASSOC);
        
        $html .= '
            <table class="data">
                <thead>
                    <tr>
                        <th>Ward</th>
                        <th>Code</th>
                        <th>PUs</th>
                        <th>Results</th>
                        <th>Verified</th>
                        <th>Coordinators</th>
                        <th>Rate</th>
                    </tr>
                </thead>
                <tbody>';
        foreach ($wards as $ward) {
            $rate = $ward['total_pus'] > 0 ? round(($ward['total_results'] / $ward['total_pus']) * 100, 1) : 0;
            $badge_class = $rate >= 70 ? 'badge-success' : ($rate >= 40 ? 'badge-warning' : 'badge-danger');
            $html .= '
                    <tr>
                        <td>' . htmlspecialchars($ward['ward_name']) . '</td>
                        <td>' . htmlspecialchars($ward['code']) . '</td>
                        <td>' . number_format($ward['total_pus']) . '</td>
                        <td>' . number_format($ward['total_results']) . '</td>
                        <td>' . number_format($ward['verified_results']) . '</td>
                        <td>' . number_format($ward['coordinators']) . '</td>
                        <td><span class="badge ' . $badge_class . '">' . $rate . '%</span></td>
                    </tr>';
        }
        $html .= '
                </tbody>
            </table>';
            
    } elseif ($type === 'agent_report') {
        // Agent Report
        $html .= '<h2>Agent Report</h2>';
        
        $sql = "
            SELECT 
                u.first_name,
                u.last_name,
                u.email,
                u.status,
                pu.name as pu_name,
                w.name as ward_name,
                COUNT(ra.id) as total_results,
                COUNT(CASE WHEN ra.status IN ('verified', 'approved') THEN 1 END) as verified_results
            FROM users u
            JOIN roles r ON u.role_id = r.id
            LEFT JOIN polling_units pu ON u.pu_id = pu.id
            LEFT JOIN wards w ON pu.ward_id = w.id
            LEFT JOIN results_ec8a ra ON ra.agent_id = u.id
            WHERE u.tenant_id = ? AND u.lga_id = ?
            AND r.level = 'pu_agent'
            AND u.deleted_at IS NULL
        ";
        $params = [$tenant_id, $lga_id];
        if ($ward_id > 0) {
            $sql .= " AND w.id = ?";
            $params[] = $ward_id;
        }
        $sql .= " GROUP BY u.id, u.first_name, u.last_name, u.email, u.status, pu.name, w.name
                  ORDER BY u.first_name ASC";
        
        $stmt = $db->prepare($sql);
        $stmt->execute($params);
        $agents = $stmt->fetchAll(PDO::FETCH_ASSOC);
        
        $html .= '
            <table class="data">
                <thead>
                    <tr>
                        <th>Agent</th>
                        <th>PU</th>
                        <th>Ward</th>
                        <th>Status</th>
                        <th>Results</th>
                        <th>Verified</th>
                    </tr>
                </thead>
                <tbody>';
        foreach ($agents as $agent) {
            $html .= '
                    <tr>
                        <td>' . htmlspecialchars($agent['first_name'] . ' ' . $agent['last_name']) . '</td>
                        <td>' . htmlspecialchars($agent['pu_name'] ?? 'N/A') . '</td>
                        <td>' . htmlspecialchars($agent['ward_name'] ?? 'N/A') . '</td>
                        <td>' . ucfirst($agent['status']) . '</td>
                        <td>' . number_format($agent['total_results']) . '</td>
                        <td>' . number_format($agent['verified_results']) . '</td>
                    </tr>';
        }
        $html .= '
                </tbody>
            </table>';
    }
} catch (Exception $e) {
    $html .= '<p>Error generating report: ' . $e->getMessage() . '</p>';
    error_log("PDF Export Error: " . $e->getMessage());
}

$html .= '
    <div class="footer">
        Generated on ' . date('F j, Y g:i A') . ' | ' . APP_NAME . ' &copy; ' . date('Y') . ' All Rights Reserved.
    </div>
</body>
</html>';

header('Content-Type: text/html');
header('Content-Disposition: attachment; filename="' . $type . '_' . date('Y-m-d') . '.html"');
echo $html;
exit;
?>